/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 */

repositories {
    mavenCentral()
    google()
}

plugins {
    id("application")
    id("org.openrewrite.build.shadow") version "2.1.0"
}

version = "0.1.0"

dependencies {
    implementation("info.picocli:picocli:4.7.7")
    implementation("dev.dirs:directories:26")
    implementation("com.moandjiezana.toml:toml4j:0.7.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "dev.haruki7049.jiho.App"
}

tasks.named<Test>("test") {
    // Use TestNG for unit tests.
    useTestNG()
}

tasks.named<CreateStartScripts>("startScripts") {
    dependsOn(tasks.named("shadowJar"))
}
